#!/usr/bin/env python3
"""Generate an EPICS .db for the load harness.

The database is a mix of *quiet* (passive) analog-input records and *active*
analog-output records:

- Quiet PVs (``ai``) never change value on their own. These are the ones that
  trigger the gateway's upstream monitor-linger leak: when a downstream
  subscriber to a quiet PV goes away, the gateway's upstream monitor only
  notices on the PV's *next* update -- which never comes -- so the upstream
  TCP socket (an fd) lingers indefinitely. Subscribe/unsubscribe churn on
  these therefore accumulates fds without bound.

- Active PVs (``ao``, ``SCAN=1 second``) are writable so the loadgen can put
  to them (set DRIVE_HOT=1). A put changes the value, which fires an update,
  which lets the gateway retire that upstream monitor promptly when its last
  subscriber leaves -- the *contrast* case (bounded fan-out, no leak).

Config via env:
  NUM_PVS           total record count           (default 2000)
  PASSIVE_FRACTION  fraction that are quiet ai's (default 0.9)
  PV_PREFIX         name prefix                  (default "LOAD")

Writes the .db to stdout.
"""
import os
import sys

n = int(os.environ.get("NUM_PVS", "2000"))
passive_frac = float(os.environ.get("PASSIVE_FRACTION", "0.9"))
prefix = os.environ.get("PV_PREFIX", "LOAD")

n_passive = int(n * passive_frac)
out = sys.stdout

out.write(f"# generated by gen_db.py: {n} PVs "
          f"({n_passive} quiet ai, {n - n_passive} active ao)\n\n")

for i in range(n):
    name = f"{prefix}:PV{i:05d}"
    if i < n_passive:
        out.write(
            f'record(ai, "{name}") {{\n'
            f'    field(DESC, "quiet")\n'
            f'    field(VAL,  "{i}")\n'
            f'    field(EGU,  "u")\n'
            f'}}\n\n'
        )
    else:
        out.write(
            f'record(ao, "{name}") {{\n'
            f'    field(DESC, "active")\n'
            f'    field(VAL,  "0")\n'
            f'    field(SCAN, "1 second")\n'
            f'}}\n\n'
        )
